### ISSUE TITLE
Page errors

### ISSUE THREAD

**Issue by SKSaki** [nenuadrian/Secret-Republic-Hacking-Browser-Game-V3#20] opened 2022-08-06 03:02 UTC
Those pages are containing errors.

Links: 
https://hrpg.lscult.com/admin/view/tests   < some kind of database error.

https://hrpg.lscult.com/admin/view/attacks   < error, database i think.

https://hrpg.lscult.com/admin/view/errors    < ironically enough errors show a database error :))

https://hrpg.lscult.com/profile   <weird overlays?

https://hrpg.lscult.com/forum    <forums with "n" threads. Where threads?

https://hrpg.lscult.com/admin/view/shop   < 404

https://hrpg.lscult.com/admin/view/attacks/hacker/18150       < error with db, might be related to second link.

https://hrpg.lscult.com/admin/view/attacks/hacker/18150/logs/show      <same as above

https://hrpg.lscult.com/support   < where captcha?

https://hrpg.lscult.com/alpha_coins  < smol error.

https://hrpg.lscult.com/admin/view/manageQuest/qid/82   < weirdly formatted on mobile.
 
https://hrpg.lscult.com/social < 404

https://hrpg.lscult.com/faq/?p=14  <404

https://hrpg.lscult.com/skills///  < skills not increasing when spending points.

**Comment by nenuadrian** [comment] 2022-08-06 14:42
Will not deal with layout issues - some may be because that's how I originally thought it looked good and it doesn't haha

For faq that might be legacy code, removed the text that points to it: https://github.com/nenuadrian/Secret-Republic-Hacking-Browser-Game-V3/commit/c86f4f6cb4e364894a952553b07314f8ff7acfab

Frequently asked questions exists but not content for formatting text anymore: https://hrpg.lscult.com/frequently-asked-questions

**Comment by nenuadrian** [comment] 2022-08-06 14:43
For captcha, have you created and added your key here? https://github.com/nenuadrian/Secret-Republic-Hacking-Browser-Game-V3/blob/master/includes/constants/constants.php#L20

**Comment by nenuadrian** [comment] 2022-08-06 14:46
For forum threads, I have deleted all of them before putting the game as open-source. But I forgot to update some of the database details so the numbers are correct.

Fixed now in SQL: https://github.com/nenuadrian/Secret-Republic-Hacking-Browser-Game-V3/commit/dc123cca3504bd92a605740d5dc498bd2a618ff2

**Comment by nenuadrian** [comment] 2022-08-06 14:47
I have deleted the social integration to not support it, so deleting any references to it

**Comment by nenuadrian** [comment] 2022-08-06 15:25
There was a bug on the skills page! Fixed it on your host and in the repository, also formatter the file so you can't see exactly where but it was     

`$skillsData = $this->db->where('uid', $uid)->where('skill', $skill)`

Should have been

`    $skillsData = $this->db->where('uid', $uid)`

**Comment by nenuadrian** [comment] 2022-08-06 15:27
If you make me an admin (cardinal), I can have a look at the admin pages.

**Comment by nenuadrian** [comment] 2022-08-06 15:46
You would also need to update the keys in public_html/includes/class/recaptchalib.php at the top for captcha to work i expect - might remove it entirely and leave it to those that want it to add it

**Comment by nenuadrian** [comment] 2022-08-06 16:00
Tests for admin are not a thing anymore - deleting it

**Comment by nenuadrian** [comment] 2022-08-06 16:03
Fixed the admin attacks page: https://github.com/nenuadrian/Secret-Republic-Hacking-Browser-Game-V3/commit/444dd5a54b9591637043f63326cac9c4358568c0

**Comment by nenuadrian** [comment] 2022-08-06 16:06
Fixed admin debug errors, debug_errors table is called debug_404_errors

**Comment by nenuadrian** [comment] 2022-08-06 16:10
https://hrpg.lscult.com/admin/view/shop < 404

This link should just not haven been there: https://github.com/nenuadrian/Secret-Republic-Hacking-Browser-Game-V3/commit/5be024a3c4fe7ed9ab57fabc6eca144b32ea80b6

**Comment by nenuadrian** [comment] 2022-08-06 16:11
So I believe I have addressed everything other than:

https://hrpg.lscult.com/alpha_coins < smol error.


If you can please open new issue with how to reproduce!

**Closed by nenuadrian** 2022-08-06 16:11 UTC
